baseurl = "/"
languageCode = "en-US"
title = "Nathan's Nuggets"
theme = "hugo-blog-awesome"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = 'en-us'

[markup]
[markup.highlight]
noClasses = false
[permalinks]
post = "/:year/:month/:day/:slug/"

# [[menu.main]]
# pageRef = "/"
# name = 'Home'
# url = '/'
# weight = 10
[[menu.main]]
name = 'Posts'
url = '/post/'
weight = 50
[[menu.main]]
name = "About Me"
url = "/AboutMe/"
weight = 100
[[menu.main]]
name = "Contact"
url = "/Contact/"
weight = 200
[[menu.main]]
name = "GitHub"
url = "https://github.com/nate601"
weight = 300

[Languages.en-us]
languageName = "English"
languageCode = 'en-US'
contentDir = "content"
weight = 1


[params]
description = "Nathan's Nuggets"

# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
highlightjsLang = ["r", "yaml", "csharp", "rust", "python"]
highlightjsTheme = "github"

MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
MathJaxVersion = "2.7.5"

# path to the favicon, under "static"
favicon = "favicon.ico"
rssFeedDescription = "full"
mainSection = ['post']

[Languages.en-us.params]
goToTop = true
[Languages.en-us.params.author]
intro = "Nathan's Nuggets"
name = "Nathan Button"
description = "Please see below for my delusional ramblings!"
